name: MacOS Build
on: push

jobs:
    build_and_test:
        runs-on: macos-14
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set up Zig
              uses: mlugg/setup-zig@v2
              with:
                version: 0.14.0
            
            - name: Symlink Zig to local bin
              run: |
                mkdir -p $GITHUB_WORKSPACE/zig-bin
                ln -s $(which zig) $GITHUB_WORKSPACE/zig-bin/zig
            
            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Create a virtual environment
              run: |
                uv venv --python 3.11
            
            - name: Activate the virtual environment
              run: |
                source .venv/bin/activate
            
            - name: Install build dependencies
              run: |
                uv pip install -e .
            
            - name: Test the build
              run: |
                uv run tests/test_spdx_checker.py
            
