name: MacOS Build
on: push

jobs:
    build_and_test:
        runs-on: macos-14
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set up Zig
              uses: mlugg/setup-zig@v2
              with:
                version: 0.14.0
            
            - name: Symlink Zig to local bin
              run: |
                mkdir -p $GITHUB_WORKSPACE/zig-bin
                ln -s $(which zig) $GITHUB_WORKSPACE/zig-bin/zig
            
            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python environment and install package
              run: |
                uv venv --python 3.11
                source .venv/bin/activate
                uv pip install -e .
            
            - name: Run tests
              run: |
                source .venv/bin/activate
                python tests/test_spdx_checker.py

            # New wheel building steps
            - name: Install wheel building dependencies
              run: |
                source .venv/bin/activate
                uv pip install build wheel delocate

            - name: Build wheel
              run: |
                source .venv/bin/activate
                # Set deployment target to match the actual minimum requirement
                export MACOSX_DEPLOYMENT_TARGET=14.7
                python -m build --wheel

            - name: Repair wheel with delocate
              run: |
                source .venv/bin/activate
                # Set deployment target to match the actual minimum requirement
                export MACOSX_DEPLOYMENT_TARGET=14.7
                delocate-wheel -w wheelhouse -v dist/*.whl

            - name: Test wheel installation
              run: |
                # Create a fresh environment to test the wheel
                uv venv test-env --python 3.11
                source test-env/bin/activate
                # Use --force-reinstall --no-deps to bypass platform checks if needed
                pip install --force-reinstall --no-deps wheelhouse/*.whl
                
                # Test that the package imports correctly
                python -c "import spdx_checker; print('Wheel installation successful!')"
                
                # Optionally run your tests against the wheel installation
                python tests/test_spdx_checker.py

            - name: List wheel contents (for debugging)
              run: |
                source .venv/bin/activate
                python -m zipfile -l wheelhouse/*.whl

            # Upload repaired wheel as artifact
            - name: Upload wheel as artifact
              uses: actions/upload-artifact@v4
              with:
                name: macos-wheel
                path: ./wheelhouse/*.whl