name: MacOS Build
on: push

jobs:
    build_and_test:
        runs-on: macos-14
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set up Zig
              uses: mlugg/setup-zig@v2
              with:
                version: 0.14.0
            
            - name: Symlink Zig to local bin
              run: |
                mkdir -p $GITHUB_WORKSPACE/zig-bin
                ln -s $(which zig) $GITHUB_WORKSPACE/zig-bin/zig
            
            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python environment and install package
              run: |
                uv venv --python 3.11
                source .venv/bin/activate
                uv pip install -e .
            
            - name: Run tests (expect failure)
              run: |
                source .venv/bin/activate
                if python tests/test_spdx_checker.py; then
                  echo "Test unexpectedly passed! Failing the workflow."
                  exit 1
                else
                  echo "Test failed as expected."
                fi

            - name: Install wheel building dependencies
              run: |
                source .venv/bin/activate
                uv pip install build wheel delocate

            - name: Build wheel
              run: |
                source .venv/bin/activate
                python -m build --wheel

            - name: Repair wheel with delocate
              run: |
                source .venv/bin/activate
                delocate-wheel -v ./wheelhouse/*.whl

            - name: Test wheel installation
              run: |
                uv venv test-env --python 3.11
                source test-env/bin/activate
                pip install ./wheelhouse/*.whl
                python -c "import spdx_checker; print('Wheel installation successful!')"
                if python tests/test_spdx_checker.py; then
                  echo "Test unexpectedly passed! Failing the workflow."
                  exit 1
                else
                  echo "Test failed as expected."
                fi

            - name: List wheel contents (for debugging)
              run: |
                source .venv/bin/activate
                python -m zipfile -l ./wheelhouse/*.whl

            - name: Upload wheel as artifact
              uses: actions/upload-artifact@v4
              with:
                name: macos-wheel
                path: ./wheelhouse/*.whl