name: Weekly License Scraper

on:
    schedule:
        #        ┌───────────── minute (0 - 59)
        #        │  ┌───────────── hour (0 - 23)
        #        │  │ ┌───────────── day of the month (1 - 31)
        #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
        #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
        #        │  │ │ │ │
        - cron: '0 20 * * 0' # Every Sunday at 8pm UTC
    workflow_dispatch:

jobs:
  license-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies with uv
        run: uv sync --dev

      - name: Run license_scraper.py with uv
        run: uv run python automation/license_scraper.py

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: "Update license data via license_scraper.py"
            title: "Update license data"
            body: "Automated update of license data via weekly workflow."
            branch: "auto/license-update-${{ github.run_id }}-$(date +'%Y%m%d')"
        env:
            TZ: UTC